apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: localstack-a
type: Opaque
data:
  access_key: "RHVtbXk="
  secret_key: "RHVtbXk="
---
apiVersion: ceph.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: localstack-a
  namespace: crossplane-system
spec:
  hostBase: "172.17.0.1:4566"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-a
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: localstack-b
type: Opaque
data:
  access_key: "RHVtbXk="
  secret_key: "RHVtbXk="
---
apiVersion: ceph.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: localstack-b
  namespace: crossplane-system
spec:
  hostBase: "172.17.0.1:4567"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-b
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: localstack-c
type: Opaque
data:
  access_key: "RHVtbXk="
  secret_key: "RHVtbXk="
---
apiVersion: ceph.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: localstack-c
  namespace: crossplane-system
spec:
  hostBase: "172.17.0.1:4568"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-c
      key: credentials
